# Generated by Django 6.0.2 on 2026-02-23 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bugs', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('rounds', models.PositiveIntegerField(default=0)),
                ('log', models.JSONField(blank=True, default=list)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='battles_as_attacker', to='bugs.bug')),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='battles_as_defender', to='bugs.bug')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='battles', to='locations.location')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='won_battles', to='bugs.bug')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
