# Generated by Django 6.0.2 on 2026-04-04 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
        ('bugs', '0006_remove_bug_deleted_at_alter_bug_owner'),
        ('locations', '0005_remove_location_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='attacker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_as_attacker', to='bugs.bug'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='defender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_as_defender', to='bugs.bug'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_battles', to='bugs.bug'),
        ),
    ]
