# Generated by Django 6.0.2 on 2026-04-02 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_id_alter_profile_user'),
        ('bugs', '0004_remove_bug_only_one_active_bug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_bug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bugs.bug'),
        ),
    ]
