# Generated by Django 6.0.2 on 2026-04-04 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_active_bug'),
        ('bugs', '0005_remove_bug_only_one_active_bug_bug_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active_bug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_by', to='bugs.bug'),
        ),
    ]
