# Generated by Django 6.0.2 on 2026-04-05 12:51

from django.db import migrations
from django.contrib.auth.management import create_permissions

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Profile = apps.get_model('accounts', 'Profile')
    
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None

    profile_content_type = ContentType.objects.get_for_model(Profile)
    
    can_assign_groups, _ = Permission.objects.get_or_create(
        codename='can_assign_groups',
        name='Can assign users to groups',
        content_type=profile_content_type
    )
    
    can_set_unusable_password, _ = Permission.objects.get_or_create(
        codename='can_set_unusable_password',
        name='Can set unusable password (ban)',
        content_type=profile_content_type
    )

    model_perms = {
        'Location Moderators': [
            ('locations', 'location'),
            ('locations', 'food'),
        ],
        'User Managing Moderators': [
            ('auth', 'user'),
            ('accounts', 'profile'),
        ],
        'Global Moderators': [
            ('bugs', 'bug'),
            ('battles', 'battle'),
            ('locations', 'location'),
            ('locations', 'food'),
            ('locations', 'foodevent'),
            ('auth', 'user'),
            ('accounts', 'profile'),
        ]
    }

    actions = ['view', 'add', 'change', 'delete']

    for group_name, models in model_perms.items():
        group, _ = Group.objects.get_or_create(name=group_name)
        
        for app_label, model_name in models:
            if group_name == 'User Managing Moderators':
                current_actions = ['view', 'change', 'delete']
            else:
                current_actions = actions

            for action in current_actions:
                codename = f'{action}_{model_name}'
                try:
                    permission = Permission.objects.get(codename=codename, content_type__app_label=app_label)
                    group.permissions.add(permission)
                except Permission.DoesNotExist:
                    pass
        
        if group_name == 'Global Moderators':
            group.permissions.add(can_assign_groups)
            group.permissions.add(can_set_unusable_password)
        
        if group_name == 'User Managing Moderators':
            group.permissions.add(can_set_unusable_password)

def remove_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Location Moderators', 'User Managing Moderators', 'Global Moderators']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_active_bug'),
        ('bugs', '0006_remove_bug_deleted_at_alter_bug_owner'),
        ('battles', '0002_alter_battle_attacker_alter_battle_defender_and_more'),
        ('locations', '0005_remove_location_deleted_at'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups),
    ]
