# Generated by Django 5.2.10 on 2026-04-07 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20260405_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_assign_groups', 'Can assign users to groups'), ('can_set_unusable_password', 'Can set unusable password (ban)')]},
        ),
    ]
