# Generated by Django 6.0.2 on 2026-02-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('FIRE', 'Fire'), ('WATER', 'Water'), ('EARTH', 'Earth'), ('GRASS', 'Grass')], db_index=True, max_length=10)),
                ('image_url', models.URLField(verbose_name='Location Image')),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
