# Generated by Django 6.0.2 on 2026-02-23 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('stat', models.CharField(choices=[('MAX_HP', 'Health Points'), ('ARMOR', 'Armor'), ('STRENGTH', 'Strength'), ('MOBILITY', 'Mobility'), ('HEALING_FACTOR', 'Healing Factor')], max_length=20)),
                ('increase_amount', models.PositiveIntegerField(default=1)),
                ('location', models.ManyToManyField(blank=True, related_name='foods', to='locations.location')),
            ],
        ),
        migrations.CreateModel(
            name='FoodEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('bug', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_events', to='bugs.bug')),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_events', to='locations.food')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_events', to='locations.location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
