# Generated by Django 6.0.2 on 2026-03-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_food_foodevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
