# Generated by Django 6.0.2 on 2026-04-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0004_remove_bug_only_one_active_bug_and_more'),
        ('locations', '0003_location_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='inhabitants',
            field=models.ManyToManyField(blank=True, help_text='All bugs that can be found at this location', related_name='locations', to='bugs.bug'),
        ),
    ]
