# Generated by Django 6.0.2 on 2026-04-04 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_location_inhabitants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='deleted_at',
        ),
    ]
