# Generated by Django 5.2.10 on 2026-04-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_remove_location_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image_url',
            field=models.URLField(max_length=500, verbose_name='Location Image'),
        ),
    ]
