# Generated by Django 6.0.2 on 2026-02-23 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('FIRE', 'Fire'), ('WATER', 'Water'), ('EARTH', 'Earth'), ('GRASS', 'Grass')], db_index=True, max_length=10)),
                ('max_health_points', models.PositiveIntegerField(verbose_name='Health Points')),
                ('armor', models.PositiveIntegerField()),
                ('strength', models.PositiveIntegerField()),
                ('mobility', models.PositiveIntegerField()),
                ('healing_factor', models.PositiveIntegerField()),
                ('image_url', models.URLField(verbose_name='Bug Image')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('natural_habitat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bugs', to='locations.location')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
