# Generated by Django 6.0.2 on 2026-02-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
        ('locations', '0002_food_foodevent'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bug',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='only_one_active_bug'),
        ),
    ]
