# Generated by Django 6.0.2 on 2026-03-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_bug_only_one_active_bug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
