# Generated by Django 6.0.2 on 2026-03-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_bug_deleted_at'),
        ('locations', '0003_location_deleted_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bug',
            name='only_one_active_bug',
        ),
        migrations.AddConstraint(
            model_name='bug',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('is_active',), name='only_one_active_bug'),
        ),
    ]
