# Generated by Django 6.0.2 on 2026-04-02 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_active_bug'),
        ('bugs', '0004_remove_bug_only_one_active_bug_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bug',
            name='only_one_active_bug',
        ),
        migrations.AddField(
            model_name='bug',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile'),
        ),
        migrations.RemoveField(
            model_name='bug',
            name='is_active',
        ),
    ]
