# Generated by Django 5.2.10 on 2026-04-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0006_remove_bug_deleted_at_alter_bug_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='image_url',
            field=models.URLField(max_length=500, verbose_name='Bug Image'),
        ),
    ]
